### ISSUE TITLE
Project Framework

### ISSUE THREAD

**Issue by Reg1234** [songdongsheng/Kafka.NET#2]
There's no code in the project

**Comment by songdongsheng** [comment]
project.json support:
    .NETCoreApp,Version=v1.0
    .NETStandardApp,Version=v1.6
    .NETFramework,Version=v4.5
    .NETFramework,Version=v4.6
    .NETCoreApp,Version=v1.0

Kafka.NET.csproj support:
    .NETFramework,Version=v4.5
    .NETFramework,Version=v4.6
    .NETFramework,Version=v4.6.1

**Comment by Reg1234** [comment]
Hi,

Thanks for the reply. How do I use this library with a .NetCore application, given I am getting the error above? It looks like it is not compatible, going on the screenshot 

Thanks
